### ISSUE TITLE
Provider without logo causes exception

### ISSUE THREAD

**Issue by mikeapp** [jbaiter/pdiiif#10]
Trying a Presentation 3 Manifest with a `provider` that does not contain a `logo` triggers an exception.

https://github.com/jbaiter/pdiiif/blob/c88735c3ee35d92baaf448393cbe1903509209c7/pdiiif-lib/src/convert.ts#L426  See also the previous line's use of `homepage`. It looks like these properties are being initialized to empty arrays if no value is provided in the Manifest. Debugger view:

<img width="261" alt="Screen Shot 2022-12-07 at 2 45 10 PM" src="https://user-images.githubusercontent.com/1987952/206280886-10ebc269-7d7e-4a34-ad62-5a9b311624e2.png">

Sample Manifest: https://collections.library.yale.edu/manifests/15504927
Web page of object: https://collections.library.yale.edu/catalog/15504927

**Comment by jbaiter** [comment]
Thanks for reporting! I just pushed the fixed code to the public instance, can try again (with a cleared cache)?
