### ISSUE TITLE
In some cases it can't convert iiif manifest to pdf 

### ISSUE THREAD

**Issue by andybuki** [jbaiter/pdiiif#12]
Hi,

in some  cases it can't convert iiif manifest to pdf 

![image](https://user-images.githubusercontent.com/4548460/208411067-008021f7-d4a1-4320-a190-3f9361b48008.png)

Here the link in system: https://iiif.crossasia.org/s/dllm/collections/1/manifests/16
And link to manifest itself: https://iiif.crossasia.org/s/dllm/madoc/api/manifests/16/export/3.0?manifest=https://iiif.crossasia.org/s/dllm/madoc/api/manifests/16/export/3.0

I think an issue can be, that the manifest metadata has two languages.

**Comment by jbaiter** [comment]
Thanks for reporting, this seems to be a  bug in the code that incorporates the cover page PDF into the actual PDF. Looks like I messed up the parser, will investigate!
