### ISSUE TITLE
Table of contents is duplicated for nested ranges

### ISSUE THREAD

**Issue by tristanr-cogapp** [jbaiter/pdiiif#21]
If a manifest includes nested `ranges` in its `structures` array, the generated PDF will duplicate named links to each of the canvases in the table of contents, instead of correctly displaying a single hierarchy.

**Steps to reproduce**

Using the [demo site](https://pdiiif.jbaiter.de/) with a manifest containing nested ranges in its `structures` array such as https://iiif.lib.harvard.edu/manifests/drs:4997399 generates a PDF that has _both_ the correct hierarchy and the repeated individual canvases in the table of contents. For comparison, this duplication does not display in the "Index" tab of the [Mirador demo site](https://mirador-dev.netlify.app/__tests__/integration/mirador/).

**Comment by jbaiter** [comment]
Just pushed a fix for this, when there's a `top` Range it will now be the only entry-level node in the ToC.
Thanks for reporting and sorry it took so long!
