### ISSUE TITLE
refuses to load dynamic iiif manifest from API

### ISSUE THREAD

**Issue by ch-sander** [jbaiter/pdiiif#23]
Example: https://icat.digitaldogsbody.net/iiif/dynamic/tag/EAC
Loads in Mirador: https://dlib.biblhertz.it/m3/?show=https://icat.digitaldogsbody.net/iiif/dynamic/tag/EAC
pdiiif however does not even show the preview.

The dynamic manifest is created via a tool (ICAT) developed by https://github.com/digitaldogsbody

**Comment by jbaiter** [comment]
Thank you for reporting! This is an unfortunate bug in the web interface: When determining the canvases to use for estimating the PDF size, we check for the length of *all* manifests for sampling and use all of them if there are fewer than the requested number (currently harcoded at 8).
However, we dont actually sample from all manifests, but filter for  canvases that do not deviate more than 25% from the mean pixel area of all canvases in the manifests, to make the estimate more precise.
And in your  case, that filtered list of canvases has fewer canvases than we request for sampling (5 vs 8) and so the code will eternally try to sample more here:
https://github.com/jbaiter/pdiiif/blob/main/pdiiif-lib/src/convert.ts#L217-L229

**Comment by ch-sander** [comment]
Maybe a related issue:

This PDF is generated but pages are all empty. Loads without problems in Mirador: https://projectmirador.org/embed/?iiif-content=https://icat.digitaldogsbody.net/iiif/1/manifest

![grafik](https://github.com/jbaiter/pdiiif/assets/74921235/e2c1edb9-cca4-4e0a-b3c2-1e8e664759a2)
