### ISSUE TITLE
Canvases without associated Image Service, but only an Identifier are not recognized

### ISSUE THREAD

**Issue by jbaiter** [jbaiter/pdiiif#25]
This PDF is generated but pages are all empty. Loads without problems in Mirador:
https://projectmirador.org/embed/?iiif-content=https://icat.digitaldogsbody.net/iiif/1/manifest

Manifest: https://icat.digitaldogsbody.net/iiif/1/manifest

Problematic Canvas Example:

```json
{
"id": "https://icat.digitaldogsbody.net/iiif/1/canvas/11",
"type": "Canvas",
"height": 1471,
"width": 1000,
"items": [
	{
		"id": "https://icat.digitaldogsbody.net/iiif/1/canvas/11/page",
		"type": "AnnotationPage",
		"items": [
			{
				"id": "https://icat.digitaldogsbody.net/iiif/1/canvas/11/page/image",
				"type": "Annotation",
				"motivation": "painting",
				"body": {
					"id": "https://files.transkribus.eu/Get?id=CUWUBAJLTWELOXAXSQTGJMMM&fileType=view",
					"type": "Image",
					"height": 1471,
					"width": 1000,
					"format": "image/jpg"
				},
				"target": "https://icat.digitaldogsbody.net/iiif/1/canvas/11"
			}
		]
	}
  ]
}
```

![grafik](https://github.com/jbaiter/pdiiif/assets/74921235/e2c1edb9-cca4-4e0a-b3c2-1e8e664759a2)

_Originally posted by @ch-sander in https://github.com/jbaiter/pdiiif/issues/23#issuecomment-1580866890_

**Comment by jbaiter** [comment]
The cause is actually a mistake in the Manifest: It uses the illegal `image/jpg` MIME type for the JPEG image on the Canvas annotations. The MIME type for JPEG is `image/jpeg` with an `e`, and this is what the code checks against.
@ch-sander are you in control of the icat.digitaldogsbody.net IIIF server?

**Comment by ch-sander** [comment]
Mike Bennett is. I will share this with him. Thanks for pointing out that issue.

**Comment by digitaldogsbody** [comment]
Thanks Johannes - now fixed!

**Comment by ch-sander** [comment]
Should be fixed now
