### ISSUE TITLE
Docker istallation pnpm

### ISSUE THREAD

**Issue by andybuki** [jbaiter/pdiiif#8]
Hi Johannes, thanks for this tool for the whole IIIF community,

I am unsure if this is an issue or if I need to add some settings in Dockerfile.

At the first start, I get an issue in installing of pnpm.

```
> `Step 10/23 : RUN wget -q -O - https://unpkg.com/@pnpm/self-installer | node
>  ---> Running in ac4d7615dfbf
> Downloading https://registry.npmjs.org/pnpm/-/pnpm-7.18.1.tgz
> GotError [RequestError]: connect ETIMEDOUT 104.16.24.35:443
>     at ClientRequest.<anonymous> ([stdin]:11520:22)
>     at Object.onceWrapper (node:events:642:26)
>     at ClientRequest.emit (node:events:527:28)
>     at TLSSocket.socketErrorListener (node:_http_client:454:9)
>     at TLSSocket.emit (node:events:527:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   code: 'ETIMEDOUT',
>   host: 'registry.npmjs.org',
>   hostname: 'registry.npmjs.org',
>   method: 'GET',
>   path: '/pnpm/-/pnpm-7.18.1.tgz',
>   protocol: 'https:',
>   url: 'https://registry.npmjs.org/pnpm/-/pnpm-7.18.1.tgz'
> 
> `
```
I can reach the following IP ( 104.16.24.35:443) from my server.
Do you have any ideas on how to solve it?

**Comment by andybuki** [comment]
Hi again a added:

> RUN npm install -g pnpm

instead 

> RUN wget -q -O - https://unpkg.com/@pnpm/self-installer | node

It works for me.

**Comment by jbaiter** [comment]
Looks like a problem with your Docker networking setup, the resource at the unpkg URL exists, and I can build the Docker container without any problems on multiple machines/networks 🤔
